services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://host.docker.internal:${DB_PORT}/keycloak
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}

      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    command: start-dev